version: '3.1'

services:
    app:
        image: 'kleky/ecotrack-app'
        volumes:
          - ./src/app/src:/app/src
        build: '.'
        ports:
            - 3000:4200
    api:
        image: 'kleky/ecotrack-api'
        volumes:
          - ./src/api/src:/app/src
        build: '.'
        ports:
            - 4000:4000
